server:
  port: 9090
spring:
  application:
    name: review-fetch-service

app:
#  itunes-review-api: http://localhost:9091/ae/rss/customerreviews/page={page_num}/id={app_id}/sortby=mostrecent/json
#  android-token-api: http://localhost:9091/o/oauth2/token
#  android-review-api: http://localhost:9091/androidpublisher/v3/applications/{package_name}/reviews?access_token={access_token}&maxResults=100&translationLanguage=en

  itunes-review-api: https://itunes.apple.com/ae/rss/customerreviews/page={page_num}/id={app_id}/sortby=mostrecent/json
  android-token-api: https://accounts.google.com/o/oauth2/token
  android-review-api: https://www.googleapis.com/androidpublisher/v3/applications/{package_name}/reviews?access_token={access_token}&maxResults=100&translationLanguage=en

logging:
  level:
    org:
      springframework:
        cloud:
          function: DEBUG